#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=$(getApplication)

cp -r 0.org/ 0

cp -r solution.flow/150.flow .
cp -f 150.flow/* 0/ 2>&1

runApplication blockMesh
runApplication decomposePar


#------------------------------------------------------------------------------
