#!/bin/bash
#PBS -N test_passiveScalar_200muLmin_shortInlet
#PBS -o test_passiveScalar_200muLmin_shortInlet.out
#PBS -j oe
#PBS -lselect=4:ncpus=48:mem=24gb
#PBS -lwalltime=48:00:00

module purge
module load intel-suite
module load mpi
module load gcc/6.2.0
module load openfoam/2006
source ~/OpenFOAM/OpenFOAM-v2006/etc/bashrc

cd $PBS_O_WORKDIR

mpiexec icoFoam -parallel > log.icoFoam 2>&1

#reconstructPar -latestTime > log.reconstructPar 2>&1


